In [8]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
arr[0, 0]	# 1

arr = np.array([1, 2, 3, 4])
new_arr = arr[0:3].copy()
arr[0:2] = 0
arr		# ([1, 2, 3, 4])
new_arr		# ([0, 0, 3])

zero = np.zeros(9)  # in one dimension

one = np.ones(19)  # in one dimension

zero = np.zeros( (4, 2) )  # in more dimensions

print(zero)
print(one)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
