# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [87]:
import numpy as np

def add_vectors(u, v):
    u = np.array(u)
    v = np.array(v)

    if len(u) == len(v):
        result1 = u + v
    
    else:
        result1 = 'Enter vectors with the same size'

    return result1

#add_vectors([1, 0], [1, 1]))
add_vectors([3, 4, 14], [10, 10, 10])


array([13, 14, 24])

In [88]:
def add_vectors(u, v):
    """
      >>> add_vectors([1, 0], [1, 1])
      [2, 1]
      >>> add_vectors([1, 2], [1, 4])
      [2, 6]
      >>> add_vectors([1, 2, 1], [1, 4, 3])
      [2, 6, 4]
      >>> add_vectors([11, 0, -4, 5], [2, -4, 17, 0])
      [13, -4, 13, 5]
      >>> a = [1, 2, 3]
      >>> b = [1, 1, 1]
      >>> add_vectors(a, b)
      [2, 3, 4]
      >>> a
      [1, 2, 3]
      >>> b
      [1, 1, 1]
    """
    pass


Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [89]:
# I inserted this cell 

def scalar_mult(s, v):
    v = np.array(v)
    result2 = s * v
    return result2

scalar_mult(40, [1, 2, 10])

array([ 40,  80, 400])

In [2]:
def scalar_mult(s, v):
    """
      >>> scalar_mult(5, [1, 2])
      [5, 10]
      >>> scalar_mult(3, [1, 0, -1])
      [3, 0, -3]
      >>> scalar_mult(7, [3, 0, 5, 11, 2])
      [21, 0, 35, 77, 14]
      >>> a = [1, 2, 3]
      >>> scalar_mult(4, a)
      [4, 8, 12]
      >>> a
      [1, 2, 3]
    """
    pass

Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [90]:
def dot_product(u, v):
    u = np.array(u)
    v = np.array(v)

    if len(u) == len(v):
        result3 = np.dot(u, v)
    
    else:
        result3 = 'Enter vectors with the same size'

    return result3

#dot_product([1, 0], [1, 1])
dot_product([2, 2, 2], [5, 5, 5])
#dot_product([2, 0, -1, 1], [1, 5, 2, 0])

30

In [3]:
def dot_product(u, v):
    """
      >>> dot_product([1, 1], [1, 1])
      2
      >>> dot_product([1, 2], [1, 4])
      9
      >>> dot_product([1, 2, 1], [1, 4, 3])
      12
      >>> dot_product([2, 0, -1, 1], [1, 5, 2, 0])
      0
    """
    pass

## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [77]:
def copy_matrix(matrix):
    matrix = np.array(matrix)
    return matrix 

# #copy_matrix([[1, 2], [3, 4]])
# #copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])

m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
copyofm = copy_matrix(m)
# copyofm

for row_num, row in enumerate(copyofm):
    for col_num, col_val in enumerate(row):
        copyofm[row_num][col_num] = 42

copyofm


array([[42, 42, 42],
       [42, 42, 42],
       [42, 42, 42]])

In [4]:
def copy_matrix(matrix):
    """
      >>> copy_matrix([[1, 2], [3, 4]])
      [[1, 2], [3, 4]]
      >>> copy_matrix([[1, 2, 3], [4, 5, 6]])
      [[1, 2, 3], [4, 5, 6]]
      >>> copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
      [[1, 2], [3, 4], [5, 6], [7, 8]]
      >>> m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> copyofm = copy_matrix(m)
      >>> copyofm
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> for row_num, row in enumerate(copyofm):
      ...     for col_num, col_val in enumerate(row):
      ...         copyofm[row_num][col_num] = 42
      ...
      >>> copyofm
      [[42, 42, 42], [42, 42, 42], [42, 42, 42]]
      >>> m
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
    """
    pass

In [125]:
# I inserted this cell 

# Any of the following can be sed to insert a row to a Matrix:
# 1. numpy.vstack()       2. numpy.append()       3. numpy.r_()       4. numpy.insert()

def add_row(matrix):


    initial_matrix = np.array(matrix)

    size_of_row = initial_matrix.shape[1]
    row = size_of_row * [0]
    matrix.append(row)

    initial_matrix = np.array(matrix)
    final_matrix = np.array(matrix)

    return final_matrix

add_row([[1, 2, 3, 4], [4, 5, 6, 3]])
add_row([[1], [4]])   


array([[1],
       [4],
       [0]])

In [130]:
# I inserted this cell 

def add_row(matrix):
    initial_matrix = np.array(matrix)

    size_of_row = initial_matrix.shape[1]
    row = size_of_row * [0]
    
    last_row = np.array(row)
    
    final_matrix = np.vstack([initial_matrix, last_row])

    return final_matrix

add_row([[1, 2, 3, 4], [4, 5, 6, 3]])
add_row([[2, 3, 4], [4, 5, 6]])
#add_row([[1], [4]])

array([[2, 3, 4],
       [4, 5, 6],
       [0, 0, 0]])

In [5]:
def add_row(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_row(m)
      [[0, 0], [0, 0], [0, 0]]
      >>> n = [[3, 2, 5], [1, 4, 7]]
      >>> add_row(n)
      [[3, 2, 5], [1, 4, 7], [0, 0, 0]]
      >>> n
      [[3, 2, 5], [1, 4, 7]]
    """
    pass

In [158]:
# I inserted this cell 

def add_column(matrix):
    
    initial_matrix = np.array(matrix)

    length_of_column = initial_matrix.shape[0]
    new_column_list = length_of_column * [0]

    new_column = np.array([new_column_list])
    new_column.T

    final_matrix = np.append(initial_matrix, new_column.T, axis=1)

    return final_matrix

add_column([[0, 0, 1], [0, 0, 2]])
add_column([[0, 0, 1], [0, 0, 2], [0, 0, 1], [0, 0, 2]])

n = [[3, 2], [5, 1], [4, 7]]
add_column(n)





array([[3, 2, 0],
       [5, 1, 0],
       [4, 7, 0]])

In [6]:
def add_column(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_column(m)
      [[0, 0, 0], [0, 0, 0]]
      >>> n = [[3, 2], [5, 1], [4, 7]]
      >>> add_column(n)
      [[3, 2, 0], [5, 1, 0], [4, 7, 0]]
      >>> n
      [[3, 2], [5, 1], [4, 7]]
    """
    pass

Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [161]:
# I added this cell

def add_matrices(m1, m2):
    first_matrix = np.array(m1)
    second_matrix = np.array(m2)
    final_matrix = first_matrix + second_matrix
    return final_matrix

a = [[1, 2], [3, 4]]
b = [[2, 2], [2, 2]]
add_matrices(a, b)

c = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
d = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
add_matrices(c, d)


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [84]:
def add_matrices(m1, m2):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> b = [[2, 2], [2, 2]]
      >>> add_matrices(a, b)
      [[3, 4], [5, 6]]
      >>> c = [[8, 2], [3, 4], [5, 7]]
      >>> d = [[3, 2], [9, 2], [10, 12]]
      >>> add_matrices(c, d)
      [[11, 4], [12, 6], [15, 19]]
      >>> c
      [[8, 2], [3, 4], [5, 7]]
      >>> d
      [[3, 2], [9, 2], [10, 12]]
   """
    pass

Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [86]:
# I inserted this cell

import numpy as np 

def scalar_mult(s, m):
    m = np.array(m)
    result5 = s * m
    return result5 

scalar_mult(10, [[1, 2, 8], [3, 4, 0]])


array([[10, 20, 80],
       [30, 40,  0]])

In [9]:
def scalar_mult(s, m):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> scalar_mult(3, a)
      [[3, 6], [9, 12]]
      >>> b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
      >>> scalar_mult(10, b)
      [[30, 50, 70], [10, 10, 10], [0, 20, 0], [20, 20, 30]]
      >>> b
      [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
    """
    pass

Write functions row_times_column and matrix_mult:

In [189]:
# I inserted this cell
def row_times_column(m1, row, m2, column):

    matrix1 = np.array(m1)
    m1_row = matrix1[row]
    first_matrix_row = np.array(m1_row)

    matrix2 = np.array(m2)
    m2_column = matrix2[: , column]
    second_matrix_column = np.array([m2_column])

    final_product = np.dot(first_matrix_row, second_matrix_column.T)

    return final_product

row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)

row_times_column([[3, 5, 7], [1, 1, 1], [4, 2, 4]], 2, [[3, 5, 7], [1, 1, 4], [0, 2, 3]], 2)



array([48])

In [10]:
def row_times_column(m1, row, m2, column):
    """
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
      19
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
      22
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
      43
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)
      50
    """
    pass

In [191]:
# I inserted this cell 

def matrix_mult(m1, m2):
    matrix1 = np.array(m1)
    matrix2 = np.array(m2)
    final_matrix = np.dot(m1, m2)
    return final_matrix

matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])

array([[31, 19],
       [85, 55]])

In [13]:
def matrix_mult(m1, m2):
    """
      >>> matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
      [[19, 22], [43, 50]]
      >>> matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
      [[31, 19], [85, 55]]
      >>> matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])
      [[39, 54, 69], [13, 23, 33], [14, 19, 24]]
    """
    pass

Write a function transpose that takes a matrix as an argument and returns is transpose:

In [72]:
# I inserted this cell 

def transpose(m):
    m = np.array(m)
    return m.T

transpose([[3, 4, 6], [1, 5, 9]])


array([[3, 1],
       [4, 5],
       [6, 9]])

In [15]:
def transpose(m):
    """
     >>> m = [[3, 4, 6]]
     >>> transpose(m)
     [[3], [4], [6]]
     >>> m
     [3, 4, 6]
     >>> m = [[3, 4, 6], [1, 5, 9]]
     >>> transpose(m)
     [[3, 1], [4, 5], [6, 9]]
   """
    pass