#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [2]:
import numpy as np

def min_max(integer):

    random = np.random.normal(size=(integer,integer))
    minValue_and_maxValue = np.array([random.min(), random.max()])

    return minValue_and_maxValue

min_max(10)

array([-2.12694299,  3.07110881])

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [11]:
# I did this in two different ways. 
# I struggled with the first on, later I was able to find an easier way. 
# Though I think the second one is cleaner, but I want to keep both. 

def myMatrix(length):

    matrix = np.zeros([length, length])

    matrix[0] = 1
    matrix[-1] = 1

    matrix = matrix.T

    matrix[0] = 1
    matrix[-1] = 1

    return matrix

myMatrix(10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
def newMatrix(length):
    
    onlyOneFirst = np.ones([length, length])
    onlyOneFirst[1:-1, 1:-1] = 0

    return onlyOneFirst

newMatrix(10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])