#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [2]:
import numpy as np 
arrayA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('Before Swap\n', arrayA)

arrayA[[0,2]] = arrayA[[2,0]]

print('\nAfter After\n',arrayA)

Before Swap
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After After
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [3]:
arrayA = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
average = np.cumsum(arrayA)

print(average)

[ 1  3  6 10 15 21 28 36 45]
